server:
  port: 9001

spring:
  application:
    name: jt-cart

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

#feign集成hystrix必须开启
feign:
  hystrix:
    enabled: true

logging:
  level:
    root: INFO
