server:
  port: 7900

spring:
  application:
    name: jt-sso-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.110:3306/jtdb
    username: root
    password: root
  redis:
    host: 192.168.195.110
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.si56baqi.sso.pojo
  mapperLocations: classpath:mybatis/mappers/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  eureka:
    enabled: true

logging:
  level:
    cn.jt.sso.mapper: debug
